modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_credits}"
description = '''
${mod_description}
'''
logoFile = "resources/assets/braverbundles/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "midnightlib"
type = "optional"
versionRange = "[1.6.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "braverbundles.mixins.json"
